services:
    debpkg-dev:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: debpkg-dev
        volumes:
            - ./PKGS:/root/PKGS
        tty: true
